services:
  my-agent:
    # image: my-agent-my-agent
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 5000:5000
    volumes:
      - ./:/app
    # deploy:
    #   replicas: 3